export enum QueryID {
  eventMagicTickets,
  ORDER_DATE = 'order_Date',
  ORDER_ID = 'order_ID',
  ORDER_STATUS = 'order_Status',
  PRODUCT_NAME = 'product_Name',
  VARIATION_NAME = 'variation_Name',
  TICKET_ID = 'ticket_ID',
  TICKET_NUMBER = 'ticket_Number',
  TICKET_PRICE = 'ticket_Price',
  ADMISSION_STATUS = 'admission_Status',
  ATTENDEE = 'attendee',
  ATTENDEE_FIRST_NAME = 'attendee_Name',
  ATTENDEE_LAST_NAME = 'attendee_LastName',
  ATTENDEE_EMAIL = 'attendee_Email',
  ATTENDEE_PHONE = 'attendee_Telephone',
  PURCHASER = 'purchaser',
  PURCHASER_FIRST_NAME = 'purchaser_FirstName',
  PURCHASER_LAST_NAME = 'purchaser_LastName',
  PURCHASER_EMAIL = 'purchaser_Email',
  PURCHASER_PHONE = 'purchaser_Phone',
  CREATED_MANUALLY = 'created_Manually',
  PAYMENT_METHOD = 'payment_Method',
  PAYMENT_TYPE = 'payment_Type',
}