import './globals.css';
import { ApolloWrapper } from "../lib/apollo-wrapper";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="es" suppressHydrationWarning>
        <body className={inter.className}>
          <ApolloWrapper>{children}</ApolloWrapper>
        </body>
      </html>
  );
}
